### ISSUE TITLE
Client error: 400

### ISSUE THREAD

**Issue by cainearized** [tomarc3/node-red-contrib-lametric-notification#1]
Hi, I am very pleased, that somebody gets in touch with LaMetric and Node-Red.

If I create a flow with a simple Inject-input it works only one time, when I trigger the Input. After that my LaMetric brightness turns really dark and if I trigger the input a second time, I get a "Client error:400" and nothing happens.

Sorry, english is not my native language :)

Best regards!

**Comment by tomarc3** [comment]
Hi, 
Sorry for the late response. I am aware of that problem, I can reproduce it.
I'm going to fix the problem asap.
Best regards.

**Comment by tomarc3** [comment]
Hi,
I've just published v0.1.1 to the npm repository. This should fix the problem.
Best regards.
